// Generated by gencpp from file ros_tutorials/MsgTutorial.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIALS_MESSAGE_MSGTUTORIAL_H
#define ROS_TUTORIALS_MESSAGE_MSGTUTORIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tutorials
{
template <class ContainerAllocator>
struct MsgTutorial_
{
  typedef MsgTutorial_<ContainerAllocator> Type;

  MsgTutorial_()
    : radius(0.0)
    , velocity(0.0)
    , direction(false)  {
    }
  MsgTutorial_(const ContainerAllocator& _alloc)
    : radius(0.0)
    , velocity(0.0)
    , direction(false)  {
  (void)_alloc;
    }



   typedef float _radius_type;
  _radius_type radius;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef uint8_t _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::ros_tutorials::MsgTutorial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tutorials::MsgTutorial_<ContainerAllocator> const> ConstPtr;

}; // struct MsgTutorial_

typedef ::ros_tutorials::MsgTutorial_<std::allocator<void> > MsgTutorial;

typedef boost::shared_ptr< ::ros_tutorials::MsgTutorial > MsgTutorialPtr;
typedef boost::shared_ptr< ::ros_tutorials::MsgTutorial const> MsgTutorialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tutorials::MsgTutorial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tutorials::MsgTutorial_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_tutorials::MsgTutorial_<ContainerAllocator1> & lhs, const ::ros_tutorials::MsgTutorial_<ContainerAllocator2> & rhs)
{
  return lhs.radius == rhs.radius &&
    lhs.velocity == rhs.velocity &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_tutorials::MsgTutorial_<ContainerAllocator1> & lhs, const ::ros_tutorials::MsgTutorial_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorials::MsgTutorial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorials::MsgTutorial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorials::MsgTutorial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorials::MsgTutorial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorials::MsgTutorial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorials::MsgTutorial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tutorials::MsgTutorial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2a72e9fb638e09d22ae8b75214c3711";
  }

  static const char* value(const ::ros_tutorials::MsgTutorial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2a72e9fb638e09dULL;
  static const uint64_t static_value2 = 0x22ae8b75214c3711ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tutorials::MsgTutorial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tutorials/MsgTutorial";
  }

  static const char* value(const ::ros_tutorials::MsgTutorial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tutorials::MsgTutorial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 radius\n"
"float32 velocity\n"
"bool direction\n"
;
  }

  static const char* value(const ::ros_tutorials::MsgTutorial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tutorials::MsgTutorial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radius);
      stream.next(m.velocity);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgTutorial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tutorials::MsgTutorial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tutorials::MsgTutorial_<ContainerAllocator>& v)
  {
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TUTORIALS_MESSAGE_MSGTUTORIAL_H
